import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';
config.autoAddCss = false;

const nunito = Nunito({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`} data-testid="layout">
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
